server:
  port: 4042
spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: user
      password: root
  #  zipkin:
  #    enabled: true
  #    base-url: http://localhost:9411
  #    service:
  #      name: card-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: studentcarduser
      password: root
      database: studentcard
#  security:
#    user:
#      name: kullanici
#      password: 12345