server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}
      routes:
        #Auth service routes
        - id: auth-service
          uri: http://localhost:4040
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth-service-application
                fallbackUri: forward:/fallback/auth
         #User service route
        - id: user-service
          uri: http://localhost:4041
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user-service-application
                fallbackUri: forward:/fallback/user
        #Mail service route
        - id: mail-service
          uri: http://localhost:4043
          predicates:
            - Path=/mail/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: mail-service-application
                fallbackUri: forward:/fallback/mail
          #Card service routes
        - id: card-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card